// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhY6jqwl1GATd3qS48WhZUJ0rYGRDJ6wg',
    appId: '1:942937440721:web:421265bf295fc6609d60f0',
    messagingSenderId: '942937440721',
    projectId: 'notes-dicoding-aa774',
    authDomain: 'notes-dicoding-aa774.firebaseapp.com',
    storageBucket: 'notes-dicoding-aa774.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDskuwAovzgXtvmZXqQzogx7qC9NtB0bGU',
    appId: '1:942937440721:android:0936f6b252953e069d60f0',
    messagingSenderId: '942937440721',
    projectId: 'notes-dicoding-aa774',
    storageBucket: 'notes-dicoding-aa774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA95Vdg3_AFONDeRgJG1xPysdD1vuoz7A',
    appId: '1:942937440721:ios:3d54726be9c6df8f9d60f0',
    messagingSenderId: '942937440721',
    projectId: 'notes-dicoding-aa774',
    storageBucket: 'notes-dicoding-aa774.appspot.com',
    iosBundleId: 'com.example.notesDicoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA95Vdg3_AFONDeRgJG1xPysdD1vuoz7A',
    appId: '1:942937440721:ios:4eb5a715f0f10e079d60f0',
    messagingSenderId: '942937440721',
    projectId: 'notes-dicoding-aa774',
    storageBucket: 'notes-dicoding-aa774.appspot.com',
    iosBundleId: 'com.example.notesDicoding.RunnerTests',
  );
}
